config/routes.rb
Rails.application.routes.draw do
  resources :nine_things

  root to: "nine_things#index"
end

app/models/nine_thing.rb
class NineThing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nine_things_controller.rb
class NineThingsController < ApplicationController
  before_action :set_nine_thing, only: [:show, :edit, :update, :destroy]

  # GET /nine_things
  # GET /nine_things.json
  def index
    @nine_things = NineThing.all
  end

  # GET /nine_things/1
  # GET /nine_things/1.json
  def show
  end

  # GET /nine_things/new
  def new
    @nine_thing = NineThing.new
  end

  # GET /nine_things/1/edit
  def edit
  end

  # POST /nine_things
  # POST /nine_things.json
  def create
    @nine_thing = NineThing.new(nine_thing_params)

    respond_to do |format|
      if @nine_thing.save
        format.html { redirect_to @nine_thing, notice: 'Nine thing was successfully created.' }
        format.json { render :show, status: :created, location: @nine_thing }
      else
        format.html { render :new }
        format.json { render json: @nine_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nine_things/1
  # PATCH/PUT /nine_things/1.json
  def update
    respond_to do |format|
      if @nine_thing.update(nine_thing_params)
        format.html { redirect_to @nine_thing, notice: 'Nine thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @nine_thing }
      else
        format.html { render :edit }
        format.json { render json: @nine_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nine_things/1
  # DELETE /nine_things/1.json
  def destroy
    @nine_thing.destroy
    respond_to do |format|
      format.html { redirect_to nine_things_url, notice: 'Nine thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nine_thing
      @nine_thing = NineThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nine_thing_params
      params.require(:nine_thing).permit(:name, :nine_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nine_things_helper.rb
module NineThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
    <h1>All the NineThings!!</h1>
    <h2>Let's get over 9000 NineThings!</h2>
    <h2>Over 9000!!!</h2>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/nine_things/_form.html.erb
<%= form_for(@nine_thing) do |f| %>
  <% if @nine_thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nine_thing.errors.count, "error") %> prohibited this nine_thing from being saved:</h2>

      <ul>
      <% @nine_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nine_number %><br>
    <%= f.number_field :nine_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nine_things/edit.html.erb
<h1>Editing nine_thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @nine_thing %> |
<%= link_to 'Back', nine_things_path %>

app/views/nine_things/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nine number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nine_things.each do |nine_thing| %>
      <tr>
        <td><%= nine_thing.name %></td>
        <td><%= nine_thing.nine_number %></td>
        <td><%= link_to 'Show', nine_thing %></td>
        <td><%= link_to 'Edit', edit_nine_thing_path(nine_thing) %></td>
        <td><%= link_to 'Destroy', nine_thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nine thing', new_nine_thing_path %>

app/views/nine_things/new.html.erb
<h1>New nine_thing</h1>

<%= render 'form' %>

<%= link_to 'Back', nine_things_path %>

app/views/nine_things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nine_thing.name %>
</p>

<p>
  <strong>Nine number:</strong>
  <%= @nine_thing.nine_number %>
</p>

<%= link_to 'Edit', edit_nine_thing_path(@nine_thing) %> |
<%= link_to 'Back', nine_things_path %>